services:
  postgres:
    image: postgres:15
    container_name: odoo-postgres-parque
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      TZ: America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17
    container_name: odoo-parque
    depends_on:
      - postgres
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: odoo
      TZ: America/Bogota
      LANG: es_ES
      LANGUAGE: es_ES.UTF-8
    command: ["odoo", "-i", "base,website", "-d", "odoo", "--without-demo=all", "--load-language=es_ES"]
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./custom_primary_variables.scss:/usr/lib/python3/dist-packages/odoo/addons/web/static/src/scss/primary_variables.scss:ro
      - ./custom_webclient_templates.xml:/usr/lib/python3/dist-packages/odoo/addons/web/views/webclient_templates.xml:ro
      - ./custom_report_templates.xml:/usr/lib/python3/dist-packages/odoo/addons/web/views/report_templates.xml:ro
      - ./custom_home_bypass.py:/usr/lib/python3/dist-packages/odoo/addons/web/controllers/home.py:ro
    restart: unless-stopped

volumes:
  postgres_data:
  odoo_data: